apiVersion: v1
kind: Pod
metadata:
  labels:
    app: "htree_parser"
    createId: "{{ uuid }}"
    createdBy: pdectl
    createdByUser: wangqiang
    runByUser: '{{ .CliArgs.String "username" }}'
    runByPdectlVersion: "{{ .CliArgs.App.Version }}"
    runnerAddress: "{{ .RunnerAddress }}"
    createdTime: "{{ .CreatedTime }}"
    pdeVersion: "v0.1.2"
    useWebEditor: "false"
    webEditorPort: 0
    webEditorType: ""
  name: "htree_parser"
  annotations:
    pdectl.douban.com/cfg/exec-cmd: '{{ .CliArgs.String "exec-default-cmd" }}'
spec:
  containers:
    - name: "main"
      env:
        - name: HOSTNAME
          value: "htree_parser-main"
      image: "docker.douban/sa/pde-go-cli:latest-1.18-v2"
      ports:
      volumeMounts:
        # mount go path src to container go path
        - mountPath: /go/src/
          name: go-path-src
        # mount code folder
        - mountPath: /home/project/
          name: code
        - mountPath: /root/
          name: userhome
        - mountPath: /fuse:rslave
          name: fuse
        - mountPath: /data
          name: beansdb-data-dir
      workingDir: /home/project
    - name: beansdb
      image: docker.douban/platform/gobeansdb:latest
      workingDir: /data/
      volumeMounts:
        - mountPath: /data
          name: beansdb-data-dir
  restartPolicy: Never
  volumes:
    - hostPath:
        path: '{{ expandEnvVar "$GOPATH/src" }}'
        type: Directory
      name: go-path-src
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}/.doubanpde/data/beansdb/'
        type: DirectoryOrCreate
      name: beansdb-data-dir
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}'
        type: Directory
      name: code
    - hostPath:
        path: '{{ expandEnvVar "$HOME/" }}'
        type: Directory
      name: userhome
    - hostPath:
        path: /fuse
        type: Directory
      name: fuse
